#!/bin/bash

if [[ $# -ne 2 ]]; then
    echo "Usage: ./run_compiler input_file output_file"
    exit
fi

./build/testc $1 ./build/out.o
clang++ build/out.o -Wall -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -L /usr/lib/gcc/x86_64-linux-gnu/11 -o $2
